comment tests out for services without unit tests

diff --git a/.github/workflows/account-service.yml b/.github/workflows/account-service.yml
--- a/.github/workflows/account-service.yml
+++ b/.github/workflows/account-service.yml
@@ -32,15 +32,15 @@ jobs:
           cache: maven
       - name: Run Maven Build Command
         run: mvn clean install -DskipTests -f account-service
-      - name: Run Maven Test
-        run: mvn test -f account-service
-      - name: Unit Test Results
-        uses: dorny/test-reporter@v1
-        if: success() || failure()
-        with:
-          name: account-service-Unit-Test-Results
-          path: "account-service/**/surefire-reports/*.xml"
-          reporter: java-junit
+#      - name: Run Maven Test
+#        run: mvn test -f account-service
+#      - name: Unit Test Results
+#        uses: dorny/test-reporter@v1
+#        if: success() || failure()
+#        with:
+#          name: account-service-Unit-Test-Results
+#          path: "account-service/**/surefire-reports/*.xml"
+#          reporter: java-junit
       - name: Build and analyze
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
diff --git a/.github/workflows/employee-service.yml b/.github/workflows/employee-service.yml
--- a/.github/workflows/employee-service.yml
+++ b/.github/workflows/employee-service.yml
@@ -34,13 +34,13 @@ jobs:
         run: mvn clean install -DskipTests -f employee-service
       - name: Run Maven Test
         run: mvn test -f employee-service
-      - name: Unit Test Results
-        uses: dorny/test-reporter@v1
-        if: success() || failure()
-        with:
-          name: employee-service-Unit-Test-Results
-          path: "employee-service/**/surefire-reports/*.xml"
-          reporter: java-junit
+#      - name: Unit Test Results
+#        uses: dorny/test-reporter@v1
+#        if: success() || failure()
+#        with:
+#          name: employee-service-Unit-Test-Results
+#          path: "employee-service/**/surefire-reports/*.xml"
+#          reporter: java-junit
       - name: Build and analyze
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
